name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env: 
 AZURE-WEBAPP-NAME: ecommerceappnode
 AZURE_WEBAPP-PACKAGEPATH: '.'
 NODE_VERSION: '14.x'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: .
    
      - run: npm run build --if-present
        working-directory: .
      - run: npm test
        working-directory: .
        
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
      
        with: 
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      
      
     
